version: "3.9"
services:
  redis:
    image: "redis:alpine"
#    ports:
#      - "6379:6379"
    network_mode: host
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
#    ports:
#      - "5432:5432"
    network_mode: host
  dashboard:
    image: gabriellpa/dashboard-jobs:latest
#    ports:
#      - "8000:8080"
    depends_on:
      - redis
    network_mode: host
  orchestrator:
    image: gabriellpa/orchestrator-jobs:latest
#    ports:
#      - "8080"
    depends_on:
      - redis
    network_mode: host
  case-api:
    image: gabriellpa/cases-api:latest
#    ports:
#      - "8080:8080"
#      - "9090:9090"
    depends_on:
      - postgres
    network_mode: host
